package com.domain.customer.service;

import com.domain.customer.entity.Customer;
import com.domain.customer.repository.CustomerRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.Optional;

@Service
public class CustomerService {

    /**
     * This is autogenerated by Spring.
     */
    @Autowired
    CustomerRepository customerRepository;

    public Iterable<Customer> findAll(){
        return customerRepository.findAll();
    }

    public Optional<Customer> findById(Integer id){
        return customerRepository.findById(id);
    }

}
